package: nbbrowserpdf

platform:
  - linux-64
  - linux-32
  - osx-64
  - win-64
  - win-32

engine:
  - python=3.5
  - python=3.4
  - python=2.7

script:
  - conda build conda.recipe -c anaconda-nb-extensions

build_targets: conda

---

platform:
  - linux-32
  - linux-64

engine:
  - python=3.5
  - python=3.4
  - python=2.7

before_script:
  - export DISPLAY=:99.0
