name: nbbrowserpdf

channels:
- bokeh
- mutirri
- javascript

dependencies:
- anaconda-client
- bokeh
- clyent
- coverage
- cycler
- decorator
- flask
- freetype
- funcsigs
- ipykernel
- ipython
- ipython_genutils
- ipywidgets
- itsdangerous
- jinja2
- jpeg
- jsonschema
- jupyter_client
- jupyter_core
- libpng
- libsodium
- libtiff
- markupsafe
- matplotlib
- mistune
- nbconvert
- nbformat
- notebook
- nose
- numpy
- openssl
- pandas
- path.py
- pickleshare
- pillow
- pip
- pygments
- pyparsing
- pyqt
- python
- python-dateutil
- pytz
- pyyaml
- pyzmq
- qt
- requests
- setuptools
- simplegeneric
- sip
- six
- sqlite
- tk
- tornado
- traitlets
- werkzeug
- wheel
- yaml
- zeromq
- zlib
- pip:
  - bqplot
  - ghost.py
  - pypdf2
  - qgrid
