name: nbbrowserpdf

channels:
- bokeh
- mutirri
- javascript
- anaconda-nb-extensions

dependencies:
- pip:
  - bqplot
  - qgrid
- anaconda-client
- bokeh
- clyent
- coverage
- cycler
- decorator
- flask
- freetype
- funcsigs
- ghost.py
- ipykernel
- ipython
- ipython_genutils
- ipywidgets
- itsdangerous
- jinja2
- jpeg
- jsonschema
- jupyter_client
- jupyter_core
- libpng
- libsodium
- libtiff
- markupsafe
- matplotlib
- mistune
- nbconvert
- nbformat
- nose
- notebook
- numpy
- openssl
- pandas
- path.py
- pickleshare
- pillow
- pip
- pygments
- pyparsing
- pypdf2
- pyqt
- python
- python-dateutil
- pytz
- pyyaml
- pyzmq
- qt
- requests
- setuptools
- simplegeneric
- sip
- six
- sqlite
- tk
- tornado
- traitlets
- werkzeug
- wheel
- yaml
- zeromq
- zlib
