package:
  name: nbpresent
  version: 0.1.0

extra:
  channels:
    - javascript

source:
  path: ../

requirements:
  build:
    - nodejs
    - python
    - notebook
  run:
    - notebook

test:
  imports:
    - nbpresent

about:
  summary: Next generation slides for Jupyter Notebooks
  license_file: LICENSE
  license: BSD License
