package:
  name: nbpresent
  version: {{ environ.get('GIT_DESCRIBE_TAG', ' ')[1:] }}

extra:
  channels:
    - cpcloud

source:
  path: ../

requirements:
  build:
    - nodejs
    - python
    - notebook
  run:
    - python
    - notebook

test:
  imports:
    - nbpresent

about:
  summary: Next generation slides for Jupyter Notebooks
  home: https://github.com/continuumio/nbpresent
  license_file: LICENSE
  license: BSD License
