package:
  name: nbpresent
  version: {{ environ.get('GIT_DESCRIBE_TAG', ' ')[1:] }}

source:
  path: ../

requirements:
  build:
    - nodejs
    - python
    - notebook
    - jupyter
    - funcsigs
  run:
    - python
    - notebook
    - jupyter
    - funcsigs

test:
  imports:
    - notebook
    - nbpresent

about:
  summary: Next generation slides for Jupyter Notebooks
  home: https://github.com/continuumio/nbpresent
  license_file: LICENSE
  license: BSD License
